Check for return value of lnusertemp. Adjusted patch from #142806.
svn path=/trunk/KDE/kdebase/workspace/; revision=641831

diff --git a/startkde b/startkde
--- a/startkde
+++ b/startkde
@@ -233,17 +233,20 @@ if test -z "$lnusertemp"; then
   echo 'startkde: ERROR: Could not locate lnusertemp in '`kde4-config --path exe` 1>&2
 fi
 
-# Link "tmp" resource to directory in /tmp
-# Creates a directory /tmp/kde-$USER and links $KDEHOME/tmp-$HOSTNAME to it.
-"$lnusertemp" tmp >/dev/null
-
-# Link "socket" resource to directory in /tmp
-# Creates a directory /tmp/ksocket-$USER and links $KDEHOME/socket-$HOSTNAME to it.
-"$lnusertemp" socket >/dev/null
-
-# Link "cache" resource to directory in /var/tmp
-# Creates a directory /var/tmp/kdecache-$USER and links $KDEHOME/cache-$HOSTNAME to it.
-"$lnusertemp" cache >/dev/null
+# Link "tmp" "socket" and "cache" resources to directory in /tmp
+# Creates:
+# - a directory /tmp/kde-$USER and links $KDEHOME/tmp-$HOSTNAME to it.
+# - a directory /tmp/ksocket-$USER and links $KDEHOME/socket-$HOSTNAME to it.
+# - a directory /var/tmp/kdecache-$USER and links $KDEHOME/cache-$HOSTNAME to it.
+# Note: temporary locations can be overriden through the KDETMP and KDEVARTMP
+# environment variables
+for resource in tmp cache socket; do
+    if ! "$lnusertemp" $resource >/dev/null; then
+        echo 'startkde: Call to lnusertemp failed (temporary directories full?). Check your installation.'  1>&2
+        xmessage -geometry 600x100 "Call to lnusertemp failed (temporary directories full?). Check your installation."
+        exit 1
+    fi
+done
 
 # In case of dcop sockets left by a previous session, cleanup
 #dcopserver_shutdown
